name: TestPyPI & PyPI Publish

on:
  push:
    tags:
      - 'v*'          # Trigger on tag pushes like v1.0.0
  release:
    types: [published] # Trigger on published GitHub Releases

jobs:
  publish-testpypi:
    if: github.event_name == 'push'
    environment: test-release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    if: github.event_name == 'release'
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Build package
      run: |
        python -m pip install --upgrade build
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
