name: TestPyPI & PyPI Publish

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
  release:
    types: [published]        # Trigger publish-pypi on published releases

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run mypy
        run: mypy

      - name: Run ruff check
        run: ruff check

  functional-tests:
    needs: code-quality
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run functional tests
        run: pytest tests/

  integration-tests:
    needs: [code-quality, functional-tests]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis/redis-stack:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: [ "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -e .[test]

      - name: Run integration tests
        env:
          REDIS_URL: redis://localhost:6379
        run: pytest tests/integration/sentencetransformer_redis.py

  publish-testpypi:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [code-quality, functional-tests, integration-tests]
    environment: test-release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-pypi:
    if: github.event_name == 'release'
    needs: [code-quality, functional-tests, integration-tests]
    environment: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1


#name: TestPyPI & PyPI Publish
#
#on:
#  push:
#    tags:
#      - 'v*'          # Trigger on tag pushes like v1.0.0
#  release:
#    types: [published] # Trigger on published GitHub Releases
#
#jobs:
#  publish-testpypi:
#    if: github.event_name == 'push'
#    environment: test-release
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#
#    - name: Build package
#      run: |
#        python -m pip install --upgrade build
#        python -m build
#
#    - name: Publish to TestPyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        repository-url: https://test.pypi.org/legacy/
#
#  publish-pypi:
#    if: github.event_name == 'release'
#    environment: release
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      contents: read
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.11'
#
#    - name: Build package
#      run: |
#        python -m pip install --upgrade build
#        python -m build
#
#    - name: Publish to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
